version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: java -Dspring.profiles.active=local -jar app.jar
    restart: "always"